all: main

main: main.cpp Apple.cpp Board.cpp Drawable.cpp Empty.cpp Scoreboard.cpp Snake.cpp SnakeGame.cpp Time.cpp Wall.cpp Poison.cpp Gate.cpp MissionBoard.cpp Mission.cpp Speed.cpp
	g++ -g -o main main.cpp Apple.cpp Board.cpp Drawable.cpp Empty.cpp Scoreboard.cpp Snake.cpp SnakeGame.cpp Time.cpp Wall.cpp Poison.cpp Gate.cpp MissionBoard.cpp Mission.cpp Speed.cpp -lncurses